[package]
name = "modal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx_glyph = "0.17.1"
winit = "0.28.3"
env_logger = "0.10"
log = "0.4"
wgpu = "0.18"
pollster = "0.3"
wgpu_text = "0.8.5"
